* Notes
** [2014-11-04 Tue] Add ip alias: ifconfig eno1:idea 10.34.17.6
** [2014-10-07 Tue]
Authorization: Basic bmxwLXdlYmFwcDo0NkU0JDZNZ2dzeGE3Nzg2
Host: cms1
Connection: Keep-Alive
User-Agent: Sardine/146
** [2014-10-06 Mon] /usr/bin/sudo don't have the suid flag in jenkins container
** [2014-10-03 Fri]
*** docker tag ventura24/nlp-webapp rm-es-01-hh1.office.tipp24.de:443/nlp-webapp
*** docker push rm-es-01-hh1.office.tipp24.de:443/nlp-webapp
** [2014-10-03 Fri] End emacs commit log: C-x #
** [2014-09-27 Sat] GRSec (webinar)
- Don't run things as root
- Drop capabilities
- Enable user namespaces
- Get rid of shady SUID binaries
- Enable SELinux
- Use seccomp-bpf
- Get a GRSEC kernel
- Update kernels often
- Mount everything read-only
- Fence things in VMs
** [2014-09-22 Mon] Should I use a different git repository for Docker?
** [2014-09-22 Mon] C-x r b -> jump to bookmark
** [2014-09-22 Mon] C-x r m -> create bookmark
** [2014-09-22 Mon] Exit from emacsclient buffer: C-x # or (server-edit)
** [2014-09-12 Fri] WARNING: if a job does not pass tests, it screws up the release process, and SNAPSHOTs can appear in the release
** [2014-09-12 Fri] New skill: git
** [2014-09-12 Fri] New skill: architect diagrams
** [2014-09-12 Fri] New skill: electronics
** [2014-09-12 Fri] New skill: arduino
** [2014-09-12 Fri] New skill: blender
** [2014-09-12 Fri] New skill: guitar
** [2014-09-12 Fri] New skill: rubik cube
** [2014-09-12 Fri] New skill: reversing
** [2014-09-12 Fri] New skill: vim
** [2014-09-12 Fri] New skill: emacs
** [2014-09-09 Tue] Don't know how to write the question mark on emacs :(
** [2014-09-09 Tue] Question: Can Artifactory use MySQL instead of derby
** [2014-09-09 Tue] Vagrant: From the book: vagrant init precise64 http://files.vagrantup.com/precise64.box
** [2014-09-09 Tue] Vagrant: vagrant box add precise64 https://vagrantcloud.com/hashicorp/boxes/precise64/versions/2/providers/virtualbox.box
** [2014-09-09 Tue] Vagrant: config.vm.synced_folder -> compartir webapps de Tomcat
** [2014-09-09 Tue] Vagrant: config.vm.post_message -> meter versión de nlp-webapp
** [2014-09-09 Tue] C-x v =
vc-diff
git diff
** [2014-09-09 Tue] C-x v v
vc-next-action
git commit
** [2014-09-09 Tue] C-x v d
vc-directory
git status
** [2014-09-09 Tue] C-x v +
vc-update
git pull
** [2014-09-05 Fri] Remind to learn org!
* Acta 2014/10/06
** Reuniones trimestrales:
- Agenda concreta
- Con más tiempo
- Pueden facilitar información anticipadamente
** Interpretación del tema de la temperatura:
- Requisito de renovación de aire: no cumplíamos la normativa por el número de empleados.
- Se tiene menos potencia en la tercera planta.
- Se establece un equipo para mejorar este tema, compuesto por Chema, Felipe y Frannie.
- Reuniones mensuales: se dará más información sobre los datos de Ventura24 y serán más concretos.
** Z pide que "La gente se responsabilice y dé un paso adelante".
** Como respuesta al "Have your say", el 10 de octubre las propuestas ganadoras hablarán con el board.
** Propuesta de cómo atajar desavenencias con Dirección.
- Chema: Cambios en el papel de Ventura24 con respecto al grupo. Se toman decisiones locales, pero dentro de la estrategia global del grupo. Hay inquietud debida a nuestra dificultad para adaptarnos. Los cambios tienen más implicaciones positivas que las que se interpretan.
- Z: Empresa con 4 lineas de negocio que necesita un cambio cultural. Las empresas nacen y mueren.
** En las reuniones generales se puede intervenir como Comité o a título personal.
* Docker/Shipyard
** Run jenkins:
shipyard run --name acmsl/jenkins --cpus 0.3 --memory 1024 --type service --hostname jenkins --domain acm-sl.org --label service --pull --port tcp/8081:8080 -vol /home/chous/acmsl-jenkins-configs/:/home/jenkins
** Run artifactory:
shipyard run --name acmsl/artifactory --cpus 0.3 --memory 1024 --type service --hostname maven --domain acm-sl.org --label service --pull --port tcp/8082:8080 -vol /home/chous/artifactory-data/:/home/artifactory
** Stop container
shipyard stop [containerId]
** Destroy container
shipyard destroy [containerId]
** Login
shipyard login
** Run mcollective-activemq
docker run -d -P --name activemq -h activemq acmsl/mcollective-activemq:latest
*** Test:
/usr/lib/jvm/java-7-oracle/bin/java -Xms512M -Xmx512M -Dorg.apache.activemq.UseDedicatedTaskRunner=true -Dcom.sun.management.jmxremote -Djava.io.tmpdir=/var/lib/activemq/tmp -Dactivemq.classpath=/etc/activemq/instances-enabled/main -Dactivemq.home=/usr/share/activemq -Dactivemq.base=/var/lib/activemq -Dactivemq.conf=/etc/activemq/instances-enabled/main -Dactivemq.data=/var/lib/activemq/data -jar /usr/share/activemq/bin/run.jar start xbean:activemq.xml
** Run mcollective-server
docker run -d --link activemq:activemq -h mcoserver acmsl/mcollective-server:latest
** Run mcollective-client
docker run -d --link activemq:activemq -h mcoclient acmsl/mcollective-client:latest
** Remove stale containers / images
https://stackoverflow.com/questions/24733160/docker-rmi-cannot-remove-images-with-no-such-id
*** sudo docker ps -a -q | xargs -n 1 -I {} sudo docker rm {}
** Test with --selinux-enabled=true
** Write a mcollective plugin:
http://blog.mague.com/?p=382
Copy from https://github.com/puppetlabs/mcollective-package-agent.git
* Beamer
** #+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t

** Frame 1
*** Thanks to Eric Fraga                                           :B_block:BMCOL:
:PROPERTIES:
:BEAMER_COL: 0.48
:BEAMER_ENV: block
:END:
for the first viable Beamer setup in Org
*** Thanks to everyone else                                        :B_block:BMCOL:
:PROPERTIES:
:BEAMER_COL: 0.48
:BEAMER_ACT: <2->
:BEAMER_ENV: block
:END:
for contributing to the discussion
**** This will be formatted as a beamer note                              :B_note:
:PROPERTIES:
:BEAMER_env: note
:END:
** Frame 2 (no columns)
*** TODO Request
    Please test this stuff!

    
** A more complex slide
This slide illustrates the use of Beamer blocks.  The following text,
with its own headline, is displayed in a block:
*** Org mode increases productivity				    :B_block:
    :PROPERTIES:
    :BEAMER_env: theorem
    :END:
    - org mode means not having to remember LaTeX commands.
    - it is based on ascii text which is inherently portable.
    - Emacs!

    \hfill \(\qed\)


    
#+LATEX: \end{frame}
#+LATEX: { % all template changes are local to this group.
  \setbeamertemplate{navigation symbols}{}
  \begin{frame}[plain]
    \begin{tikzpicture}[remember picture,overlay]
      \node[at=(current page.center)] {
        \includegraphics[width=\paperwidth]{docker-icons.eps}
      };
    \end{tikzpicture}
  \end{frame}
}
