* Stuxnet tales

An interesting <a href="http://blogs.technet.com/b/markrussinovich/archive/2011/03/30/3416253.aspx">article</a> about using <a href="http://technet.microsoft.com/en-us/sysinternals/bb545027">sysinternals</a>' tools to dissect or analyze a <a href="http://en.wikipedia.org/wiki/Stuxnet">stuxnet</a> rootkit bundled as a driver.

It's funny the apparent <a href="http://pastebin.com/74KXCaEZ">counter-attack</a> from the so-called '<a href="http://pastebin.com/u/ComodoHacker">ComodoHacker</a>'. At least, regarding stuxnet as a 'cyberweapon', he seems to be right. <a href="http://www.techrepublic.com/blog/networking/network-admins-must-beware-of-stuxnet-a-scada-system-worm/3210">Scada</a> is a hot-spot in current security conferences.
Taking part of what the guy says seriously (I mean, there's no question about what he did, but everything else he says), I'm concerned about whether Mozilla knew about the print vulnerability and decided not to fix it. For more information about stuxnet, the "security now" (arguably not one of this blog's heavy users' favorites) podcast talked about it recently.

Anyway, for the record, using Windows is a nightmare. I don't trust Windows Firewall any longer after I started using <a href="http://www.security-projects.com/?Patriot_NG">patriot-ng</a> and it revealed much more unexpected traffic than I thought (the same applies for the iPad). Until further notice I'm affording to trust <a href="http://www.microsoft.com/security_essentials/">Security Essentials</a> because I refuse to pay for an AV, and it's not collapsing my system. Needless to say, I don't use Windows because I like it: only for certain tasks/tests/research. We <a href="http://www.theregister.co.uk/2011/03/25/spotify_malvertisement_attack/">cannot trust</a> even Spotify Free! :(
